version: '3.8'
services:
  app:
    image: kennethreitz/httpbin
    expose:
      - "80"
    networks:
      example-net:
        ipv4_address: 172.44.0.4
  kuma-dp:
    image: docker.io/kumahq/kuma-dp:1.6.0
    volumes:
      - ./token-example-app:/token-example-app
      - ./dataplane.yaml:/dataplane.yaml
    ports:
      - "10080:10080"
    command:
      - "run"
      - "--cp-address=https://host.docker.internal:5678"
      - "--dns-enabled=false"
      - "--dataplane-token-file=/token-example-app"
      - "--dataplane-file=/dataplane.yaml"
    networks:
      example-net:
        ipv4_address: 172.44.0.2
  opa:
    image: openpolicyagent/opa:latest-envoy
    command:
      - "run"
      - "--server"
      - "--config-file=/config/opa-conf.yaml"
    volumes:
      - ./opa-conf.yaml:/config/opa-conf.yaml
    expose:
      - "9191"
    networks:
      example-net:
        ipv4_address: 172.44.0.3
networks:
  example-net:
    ipam:
      config:
        - subnet: 172.44.0.0/16
