apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: kmesh-opa-demo
  annotations:
    8080.service.kuma.io/protocol: "http"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: example-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: kmesh-opa-demo
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: app
          image: kennethreitz/httpbin:latest
          ports:
          - containerPort: 80
