apiVersion: v1
kind: Secret
metadata:
  name: opa-das-config
  namespace: kuma-opa-demo
stringData:
  conf.yaml: |
    discovery:
      name: discovery
      resource: /systems/<styra-system-id>/discovery
      service: styra
    labels:
      system-id: <styra-system-id>
      system-type: kuma
    services:
    - credentials:
        bearer:
          token: <styra-token>
      name: styra
      url: https://<styra-organization-id>/v1
---
apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: kuma-opa-demo
  ## protocol annotation has been deprecated in favor of `appProtocol` (set below)
  # annotations:
    # 8080.service.kuma.io/protocol: "http"
spec:
  ports:
  - name: http
    port: 8080
    appProtocol: http
    targetPort: 80
  selector:
    app: example-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: kuma-opa-demo
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      annotations:
        kuma.io/virtual-probes: disabled
      labels:
        app: example-app
    spec:
      containers:
        - name: app
          image: kennethreitz/httpbin:latest
          ports:
          - containerPort: 80
        - name: opa
          image: openpolicyagent/opa:latest-envoy
          volumeMounts:
          - readOnly: true
            mountPath: /config
            name: opa-config
          args:
          - "run"
          - "--server"
          - "--ignore=.*"
          - "--config-file=/config/conf.yaml"
          - "--authorization=basic"
          - "--addr=http://127.0.0.1:8181"
          - "--diagnostic-addr=0.0.0.0:8282"
          livenessProbe:
            httpGet:
              path: /health?plugins
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?bundle=true
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
      - name: opa-config
        secret:
          secretName: opa-das-config
